version: "3"
services:
  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    image: anfon-syml/frontend:latest
    container_name: frontend
    ports:
      - "4200:80"
  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    image: anfon-syml/backend:latest
    container_name: frontend
    ports:
      - "4000:81"
